name: harvey

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cc:
          - gcc-9
#          - clang
#          - clang-9
          - clang-10
        go:
          - 1.15
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # see https://wiki.ubuntu.com/ToolChain
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' -y
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} rc qemu go-dep
    - name: bootstrap and build
      env:
        ARCH: amd64
        OS: linux
        CC: ${{ matrix.cc }}
        GO_VERSION: ${{ matrix.go }}
      run: ./util/ci.sh # fetches Go release and invokes bootstrap.sh + build
    - name: boot
      env:
        HARVEY: ${{github.workspace}}
      run: ./linux_amd64/bin/qtap
    - name: checkout-docs
      if: ${{ github.ref == 'refs/heads/main' && startsWith(matrix.cc, 'clang') }}
      uses: actions/checkout@v2
      with:
        repository: "harvey-os/harvey-os.github.io"
        path: ${{ github.workspace }}/harvey-os.github.io
    - name: generate-docs
      if: ${{ success() }}
      run: |
        cd ${{github.workspace }}
        sudo apt-get install -y clang-tools-10
        clang-doc \
          --output=${{ github.workspace }}/harvey-os.github.io/docs \
          --format=md \
          -p=${{ github.workspace }} \ 
          --project-name='Harvey OS' \
          --repository=https://github.com/Harvey-OS/harvey/blob/${{ github.ref }}/ \
          ${{github.workspace }}/sys/src/
        cd ${{github.workspace }}/harvey-os.github.io
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "updating docs from github.com/harvey-os/harvey/tree/${{ github.ref}}"
        git push
